version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: login_registro
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: login_registro
    ports:
      - "5401:5432"
